#!/bin/bash

if [ -n "${ZSH_VERSION}" ] ; then
    if [ -n "$(readlink ${(%):-%x})" ] ; then
        eval $(env | python "$(dirname $(readlink ${(%):-%x}))/envirou.py" $*)
    else
        eval $(env | python "$(dirname ${(%):-%x})/envirou.py" $*)
    fi
else
    if [ -n "$(readlink ${BASH_SOURCE[0]})" ] ; then
        eval $(env | python "$(dirname $(readlink ${BASH_SOURCE[0]}))/envirou.py" $*)
    else
        eval $(env | python "$(dirname ${BASH_SOURCE[0]})/envirou.py" $*)
    fi
fi
