#!/bin/bash

if [ -n "${ZSH_VERSION}" ] ; then
    # Support source-ing from zsh
    ENVIRO_ROOT=$(dirname $(readlink ${(%):-%x} || ${(%):-%x}))
else
    ENVIRO_ROOT=$(dirname $(readlink "${BASH_SOURCE[0]}" || "${BASH_SOURCE[0]}"))
fi

echo $(python "${ENVIRO_ROOT}/enviro.py" $*)
