name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-go@v2
      with:
        go-version: '>=1.17.0'
    
    - name: Build
      run: go build . 
      
    - name: Run vet
      run: |
        go vet .
    
    - name: Run tests
      run: |
        go test -coverprofile=c.out ./...
        go tool cover -html=c.out
    